using System;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Source.Mdl.Header
{
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct Header
    {
        public int Id;
        public int Version;
        public int Checksum;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
        public string Name;
        public int DataLength;
        public Vector3 EyePosition;
        public Vector3 IllumPosition;
        public Vector3 HullMin;
        public Vector3 HullMax;
        public Vector3 ViewBoundingBoxMin;
        public Vector3 ViewBoundingBoxMax;
        public StudioHDRFlags Flags;

        public int BoneCount;
        public int BoneOffset;

        public int BoneControllerCount;
        public int BoneControllerOffset;

        public int HitBoxCount;
        public int HitBoxOffset;

        public int LocalAnimCount;
        public int LocalAnimOffset;

        public int LocalSeqCount;
        public int LocalSeqOffset;

        public int ActivityListVersion;
        public int EventsIndexed;

        public int TextureCount;
        public int TextureOffset;

        public int TextureDirCount;
        public int TextureDirOffset;

        public int SkinReferenceCount;
        public int SkinReferenceFamilyCount;
        public int SkinReferenceIndex;

        public int BodyPartCount;
        public int BodyPartOffset;

        public int AttachmentCount;
        public int AttachmentOffset;

        public int LocalNodeCount;
        public int LocalNodeIndex;
        public int LocalNodeNameIndex;

        public int FlexDescriptionCount;
        public int FlexDescriptionIndex;

        public int FlexControllerCount;
        public int FlexControllerIndex;

        public int FlexRulesCount;
        public int FlexRulesIndex;

        public int InverseKinematicsChainCount;
        public int InverseKinematicsChainIndex;

        public int MouthsCount;
        public int MouthsIndex;

        public int LocalPoseParameterCount;
        public int LocalPoseParameterIndex;

        public int SurfacePropertyIndex; //308

        public int KeyValueIndex;
        public int KeyValueCount;

        public int InverseKinematicsLockCount;
        public int InverseKinematicsLockIndex;

        public float Mass;
        public int Contents;

        public int IncludeModelCount;
        public int IncludeModelIndex;

        public int VirtualModel;

        public int AnimationBlocksNameIndex;
        public int AnimationBlocksCount;
        public int AnimationBlocksIndex;

        public int AnimationBlockModel;

        public int BoneTableNameIndex;

        public int VertexBase;
        public int OffsetBase;

        public byte DirectionalDotProduct;

        public byte RootLevelOfDetail;

        public byte AllowedRootLevelsOfDetailCount;

        public byte Unused;
        public int Unused1;

        public int FlexControllerUICount;
        public int FlexControllerUIIndex;

        public int StudioHDR2Index;

        public int Unused3;
    }

    [Flags]
    public enum StudioHDRFlags
    {
        AutogeneratedHitBox = 1 << 0,
        UsesEnvironmentCubemap = 1 << 1,
        ForceOpaque = 1 << 2,
        TranslucentTwoPass = 1 << 3,
        StaticProp = 1 << 4,
        UsesFBTexture = 1 << 5,
        HasShadowLevelOfDetail = 1 << 6,
        UsesBumpMapping = 1 << 7,
        UseShadowLevelOfDetailMaterials = 1 << 8,
        Obsolete = 1 << 9,
        Unused = 1 << 10,
        NoForcedFade = 1 << 11,
        ForcePhonemeCrossfade = 1 << 12,
        ConstantDirectionalLightDot = 1 << 13,
        FlexesConverted = 1 << 14,
        BuiltInPreviewMode = 1 << 15,
        AmbientBoost = 1 << 16,
        DoNotCastShadows = 1 << 17,
        CastTextureShadows = 1 << 18
    }
}
